require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe FoodordersController do

  # This should return the minimal set of attributes required to create a valid
  # Foodorder. As you add validations to Foodorder, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all foodorders as @foodorders" do
      foodorder = Foodorder.create! valid_attributes
      get :index
      assigns(:foodorders).should eq([foodorder])
    end
  end

  describe "GET show" do
    it "assigns the requested foodorder as @foodorder" do
      foodorder = Foodorder.create! valid_attributes
      get :show, :id => foodorder.id.to_s
      assigns(:foodorder).should eq(foodorder)
    end
  end

  describe "GET new" do
    it "assigns a new foodorder as @foodorder" do
      get :new
      assigns(:foodorder).should be_a_new(Foodorder)
    end
  end

  describe "GET edit" do
    it "assigns the requested foodorder as @foodorder" do
      foodorder = Foodorder.create! valid_attributes
      get :edit, :id => foodorder.id.to_s
      assigns(:foodorder).should eq(foodorder)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Foodorder" do
        expect {
          post :create, :foodorder => valid_attributes
        }.to change(Foodorder, :count).by(1)
      end

      it "assigns a newly created foodorder as @foodorder" do
        post :create, :foodorder => valid_attributes
        assigns(:foodorder).should be_a(Foodorder)
        assigns(:foodorder).should be_persisted
      end

      it "redirects to the created foodorder" do
        post :create, :foodorder => valid_attributes
        response.should redirect_to(Foodorder.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved foodorder as @foodorder" do
        # Trigger the behavior that occurs when invalid params are submitted
        Foodorder.any_instance.stub(:save).and_return(false)
        post :create, :foodorder => {}
        assigns(:foodorder).should be_a_new(Foodorder)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Foodorder.any_instance.stub(:save).and_return(false)
        post :create, :foodorder => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested foodorder" do
        foodorder = Foodorder.create! valid_attributes
        # Assuming there are no other foodorders in the database, this
        # specifies that the Foodorder created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Foodorder.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => foodorder.id, :foodorder => {'these' => 'params'}
      end

      it "assigns the requested foodorder as @foodorder" do
        foodorder = Foodorder.create! valid_attributes
        put :update, :id => foodorder.id, :foodorder => valid_attributes
        assigns(:foodorder).should eq(foodorder)
      end

      it "redirects to the foodorder" do
        foodorder = Foodorder.create! valid_attributes
        put :update, :id => foodorder.id, :foodorder => valid_attributes
        response.should redirect_to(foodorder)
      end
    end

    describe "with invalid params" do
      it "assigns the foodorder as @foodorder" do
        foodorder = Foodorder.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Foodorder.any_instance.stub(:save).and_return(false)
        put :update, :id => foodorder.id.to_s, :foodorder => {}
        assigns(:foodorder).should eq(foodorder)
      end

      it "re-renders the 'edit' template" do
        foodorder = Foodorder.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Foodorder.any_instance.stub(:save).and_return(false)
        put :update, :id => foodorder.id.to_s, :foodorder => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested foodorder" do
      foodorder = Foodorder.create! valid_attributes
      expect {
        delete :destroy, :id => foodorder.id.to_s
      }.to change(Foodorder, :count).by(-1)
    end

    it "redirects to the foodorders list" do
      foodorder = Foodorder.create! valid_attributes
      delete :destroy, :id => foodorder.id.to_s
      response.should redirect_to(foodorders_url)
    end
  end

end
