require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe User1sController do

  # This should return the minimal set of attributes required to create a valid
  # User1. As you add validations to User1, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all user_1s as @user_1s" do
      user_1 = User1.create! valid_attributes
      get :index
      assigns(:user_1s).should eq([user_1])
    end
  end

  describe "GET show" do
    it "assigns the requested user_1 as @user_1" do
      user_1 = User1.create! valid_attributes
      get :show, :id => user_1.id.to_s
      assigns(:user_1).should eq(user_1)
    end
  end

  describe "GET new" do
    it "assigns a new user_1 as @user_1" do
      get :new
      assigns(:user_1).should be_a_new(User1)
    end
  end

  describe "GET edit" do
    it "assigns the requested user_1 as @user_1" do
      user_1 = User1.create! valid_attributes
      get :edit, :id => user_1.id.to_s
      assigns(:user_1).should eq(user_1)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new User1" do
        expect {
          post :create, :user_1 => valid_attributes
        }.to change(User1, :count).by(1)
      end

      it "assigns a newly created user_1 as @user_1" do
        post :create, :user_1 => valid_attributes
        assigns(:user_1).should be_a(User1)
        assigns(:user_1).should be_persisted
      end

      it "redirects to the created user_1" do
        post :create, :user_1 => valid_attributes
        response.should redirect_to(User1.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved user_1 as @user_1" do
        # Trigger the behavior that occurs when invalid params are submitted
        User1.any_instance.stub(:save).and_return(false)
        post :create, :user_1 => {}
        assigns(:user_1).should be_a_new(User1)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        User1.any_instance.stub(:save).and_return(false)
        post :create, :user_1 => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested user_1" do
        user_1 = User1.create! valid_attributes
        # Assuming there are no other user_1s in the database, this
        # specifies that the User1 created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        User1.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => user_1.id, :user_1 => {'these' => 'params'}
      end

      it "assigns the requested user_1 as @user_1" do
        user_1 = User1.create! valid_attributes
        put :update, :id => user_1.id, :user_1 => valid_attributes
        assigns(:user_1).should eq(user_1)
      end

      it "redirects to the user_1" do
        user_1 = User1.create! valid_attributes
        put :update, :id => user_1.id, :user_1 => valid_attributes
        response.should redirect_to(user_1)
      end
    end

    describe "with invalid params" do
      it "assigns the user_1 as @user_1" do
        user_1 = User1.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        User1.any_instance.stub(:save).and_return(false)
        put :update, :id => user_1.id.to_s, :user_1 => {}
        assigns(:user_1).should eq(user_1)
      end

      it "re-renders the 'edit' template" do
        user_1 = User1.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        User1.any_instance.stub(:save).and_return(false)
        put :update, :id => user_1.id.to_s, :user_1 => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested user_1" do
      user_1 = User1.create! valid_attributes
      expect {
        delete :destroy, :id => user_1.id.to_s
      }.to change(User1, :count).by(-1)
    end

    it "redirects to the user_1s list" do
      user_1 = User1.create! valid_attributes
      delete :destroy, :id => user_1.id.to_s
      response.should redirect_to(user_1s_url)
    end
  end

end
